# Configuration

SERIAL_PORT = 'COM24'  # Change this to your serial port
BAUD_RATE = 921600

# Packet structure constants
OW_START_BYTE = 0xAA
OW_END_BYTE = 0xDD
ID_COUNTER = 0  # Initializing the ID counter

# Packet Types
OW_ACK = 0xE0
OW_NAK = 0xE1
OW_CMD = 0xE2
OW_RESP = 0xE3
OW_DATA = 0xE4
OW_JSON = 0xE5
OW_TX7332 = 0xE6
OW_BAD_PARSE = 0xEC
OW_BAD_CRC = 0xED
OW_UNKNOWN = 0xEE
OW_ERROR = 0xEF

# Commands 
USTX_NOP = 0xB0  
USTX_PING = 0xB1
USTX_PONG = 0xB2
USTX_VERSION = 0xB3
USTX_ID = 0xB4
USTX_ECHO = 0xB5

# AFE Commands
CMD_READ_ADDR = 0xC0
CMD_WRITE_ADDR = 0xC1
CMD_WRITE_DEMO = 0xC2
CMD_VERIFY_DEMO = 0xC3
CMD_WRITE_BLOCK = 0xC4
CMD_SET_SWTRIG = 0xCA
CMD_GET_SWTRIG = 0xCB
CMD_START_SWTRIG = 0xCC
CMD_STOP_SWTRIG = 0xCD
CMD_STATUS_SWTRIG = 0xCE